### ISSUE TITLE
项目clone下载，5个test无法通过，这正常吗？

### ISSUE THREAD

**Issue by WangZishi** [oyyd/shadowsocks-js#11]
![image](https://cloud.githubusercontent.com/assets/8288105/16237488/47acd020-380f-11e6-9010-bde9c4aa7208.png)

OS: Windows 10 14367 x64
node: 6.2.2
npm: 3.10.1

**Comment by oyyd** [comment]
有，虽然部分测试会发送网络请求，但上面这几个问题与这点无关。很有可能是操作系统导致的，我会尽快测试下。

**Comment by oyyd** [comment]
> Shadowsocks-js has been tested in osx and ubuntu 14 but it's also expected to work in windows.

因为我尽可能避免了一些与操作系统环境有关的api或是文件路径等，所以我自然而然地认为在windows上也没有问题。

非常感谢指出（然而手头上并没有windows机器，先用虚拟机试试）。

**Comment by oyyd** [comment]
我在win7虚拟机, node v6.2.2上进行测试并没有发现问题。

![test](https://cloud.githubusercontent.com/assets/5847587/16461398/f099db24-3e5e-11e6-86d9-5d76143b4cc2.png)

但我解决了在windows上关闭进程的问题。 #12 

需要更多信息。

**Comment by WangZishi** [comment]
我今天又试了一下，没有问题的，我发现是因为我开着Shadowsocks的缘故。

**Comment by oyyd** [comment]
ok, 我之后会把端口被占用的error详细地抛出来，非常感谢！
