### ISSUE TITLE
想给你的东西写一个GUI工具

### ISSUE THREAD

**Issue by mrcodehang** [oyyd/shadowsocks-js#16]
你好 oyyd.
我看了你的shadowsocks-js项目后, 想写一个GUI工具
如果你不介意的话, 是否可以法邮箱给我一个安心的答复呢？、
我的邮箱:734202639@qq.com
非常感谢你的shadowsocks-js

**Comment by oyyd** [comment]
@niugeshenhua [shadowsocks-gui](https://github.com/shadowsocks/shadowsocks-gui) 不管是哪种gui，前人应该都已经做过了（也不该说是“前人”）。不过我还是很感激你有这样的想法。

其实我倒更在意别人在用的时候有没有碰到什么问题，并反馈出来，毕竟我自己的应用场景非常有限，我也没有时间多到可以去探索那些我现在不需要的应用场景。估计很多人在尝试的时候碰到问题就走了，换了别的选择，毕竟在有更成熟的项目的情况下，并没有给这个项目足够多的时间去改进。本身我也只是完全copy了clowwindy的思路，边探索边写了一份更适合现在js开发风格的代码。

**Comment by oyyd** [comment]
@niugeshenhua [shadowsocks-gui](https://github.com/shadowsocks/shadowsocks-gui) 不管是哪种gui，前人应该都已经做过了（也不该说是“前人”）。不过我还是很感激你有这样的想法。

其实我倒更在意别人在用的时候有没有碰到什么问题，并反馈出来，毕竟我自己的应用场景非常有限，我也没有时间多到可以去探索那些我现在不需要的应用场景。估计很多人在尝试的时候碰到问题就走了，换了别的选择，毕竟在有更成熟的项目的情况下，并没有给这个项目足够多的时间去改进。本身我也只是完全copy了clowwindy的思路，边探索边写了一份更适合现在js开发风格的代码。

**Comment by niugeshenhua** [comment]
@oyyd  嗯, 请问一下 你做这个shadowsocks会用到哪些知识点呢？ 我很好奇, 正想入门来着.
非常感谢哈。

**Comment by niugeshenhua** [comment]
@oyyd  还有就是我觉得他们那些gui都不是很好用....
