### ISSUE TITLE
How about  the high concurrency situation in a proxy tool?

### ISSUE THREAD

**Issue by shangxinbo** [oyyd/shadowsocks-js#20]
I wonder how much the high concurrency situation in a proxy tunnel,like shadowsocks?

**Comment by oyyd** [comment]
Do you mean comparing to the python implementation? You may want to check the [benchmark](https://github.com/oyyd/shadowsocks-js/tree/master/benchmark) but it maybe not fair to compare situation of a python process with a node process

**Comment by ShangXinbo** [comment]
I mean the high concurrency is meaningless for shadowsocks. Am I wrong?

**Comment by oyyd** [comment]
从我自己的benchmark结果来看，带宽是瓶颈。但也不是完全无意义
