### ISSUE TITLE
localssjs 可实现负载均衡么

### ISSUE THREAD

**Issue by shangxinbo** [oyyd/shadowsocks-js#21]
客户端可以实现多服务器负载均衡么，高可用的参数

**Comment by oyyd** [comment]
在客户端上，你指的是多个可选择的服务器，轮着发送请求吗？现在没有。实现这点，对请求的资源方来说，会导致请求ip变化，可能会产生问题，另外配置可能要支持多分，虽然现在看来只有密码和加密算法需要在配置里维护多分

**Comment by ShangXinbo** [comment]
对，我也发现了这个问题，所以现在来看高可用配置的优点和缺点需要另论
