### ISSUE TITLE
可以通过node_modules 引入么

### ISSUE THREAD

**Issue by shangxinbo** [oyyd/shadowsocks-js#22]
可以作为node模块引入作为程序的一部分使用么，我正在做一个node开源程序，想借助一下这个程序，想通过npm  install --save 安装为内部模块使用，而不用全局

**Comment by oyyd** [comment]
你会需要用到什么模块呢？很多时候直接开一个ss进程会更靠谱。

**Comment by ShangXinbo** [comment]
我需要一个主进程然后ss进程只是一个子进程，这样我讲ss-js作为一个依赖使用

**Comment by oyyd** [comment]
可以安装到node_modules里，然后用bin里面的文件启动。应该没问题
