### ISSUE TITLE
文档中SOCKS5 Username Password Authetication

### ISSUE THREAD

**Issue by shangxinbo** [oyyd/shadowsocks-js#26]
NOTE: This authetication is dangerous when sniffed. 这句话是什么意思

**Comment by oyyd** [comment]
我曾经想把local服务也放在远程，然后通过socks5协议的认证来识别用户，但这样的结果是未加密的内容会暴露给外部，也就失去了最基本的加密措施（协议也容易被识别）。所以告诫一下有产生同样想法的同学。
