### ISSUE TITLE
gfwlistUtils是在server端使用么？

### ISSUE THREAD

**Issue by shangxinbo** [oyyd/shadowsocks-js#27]
用惯了shadowsocks-window，觉得pacserver应该是本地运行啊，为什么会在server端
在gfwlistUtils.js 的顶部注释// NOTE: do not use these in local server，是说pac放在服务端用么？

**Comment by oyyd** [comment]
不，就是在本地，我只是习惯叫local server和remote server

**Comment by shangxinbo** [comment]
为什么会有这个注释

**Comment by oyyd** [comment]
抱歉，我理解错你的意思了。这句话的意思是，这个文件里面的代码因为是同步、耗时的代码不适合在运行时运行。他们主要用在单独的命令上。
