### ISSUE TITLE
我想知道这个程序是如何防止tcp丢包的

### ISSUE THREAD

**Issue by shangxinbo** [oyyd/shadowsocks-js#29]
我在这个库上做http层代理，发现经常会出现socket hang up问题，程序是如何控制丢包的

**Comment by oyyd** [comment]
错误处理在这里：https://github.com/oyyd/shadowsocks-js/blob/master/src/ssServer.js#L68。在这一层里并不会也不应该做额外处理。如果访问地址正常，网络也正常的话，仍旧经常出现socket hang up的话，则很可能是现在程序内有bug。
