### ISSUE TITLE
有没有办法进行全局代理

### ISSUE THREAD

**Issue by shangxinbo** [oyyd/shadowsocks-js#31]
可以设置软件代理，有没有办法象lantern一样设置全局代理，所有的软件流量都经过代理呢？

**Comment by oyyd** [comment]
全局代理需要操作系统支持，不同平台需要写不同的代码。有时间我会找找或是写一个node上的跨平台的工具，但是不一定会放到这个项目里来。

**Comment by oyyd** [comment]
在#15 中讨论
