### ISSUE TITLE
Can't bind local port!!!!!

### ISSUE THREAD

**Issue by niugeshenhua** [oyyd/shadowsocks-js#9]
root@crazyforcode:/usr/local/bin# localssjs -s 104.224.151.62 -p 9999 -l 127.0.0.1 -b 1080 -k 1234567890 -m aes-256-cfb -t 600
2016-06-16T18:39:49.330Z - error: udp_relay socket err: bind EADDRINUSE :::1080

system: linux ubuntu 14.04

When i config localssjs according to toturial, i meet this error.

**Comment by oyyd** [comment]
Hi, @niugeshenhua 

>  2016-06-16T18:39:49.330Z - error: udp_relay socket err: bind EADDRINUSE :::1080

This indicates that the ipv6 binding has failed (depending on the environment) but it would have bind the ipv4 sucessfully. I should have made these logs more clearly.

**Comment by oyyd** [comment]
@niugeshenhua Can you test whether it works and provide some more info?

**Comment by niugeshenhua** [comment]
### Thank you for your report.

My config file as follows:(password was replaced with ***********)
{
  "serverAddr": "104.224.151.62",
  "serverPort": 8083,
  "localAddr": "127.0.0.1",
  "localPort": 1080,
  "pacServerPort": 8090,
  "password": "**********",
  "timeout": 600,
  "method": "aes-256-cfb",

  "level": "warn",
  "localAddrIPv6": "::1",
  "serverAddrIPv6": "::1"
}

And my VPS has install shadowsocks for python rather than shadowsocks-js.

It has error as follows When i type "localssjs -c ./config.js".

2016-06-17T12:14:29.316Z - error: udp_relay socket err: bind EADDRINUSE :::1080

}

And my VPS has install shadowsocks for python rather than shadowsocks-js.

It has error as follows When i type "localssjs -c ./config.js".

2016-06-17T12:14:29.316Z - error: udp_relay socket err: bind EADDRINUSE :::1080

Did you need the more informations?
